In [1]:
import json
from io import StringIO
from tab_dataset import Cdataset
import ntv_pandas as npd
import pandas as pd

In [15]:
file_name = "payload_pdc.json"
with open(file_name, "r") as f:
    data = f.read()
payload = pd.read_json(StringIO(json.loads(data)), orient="record").reset_index()
#payload

In [56]:
#file_name = "payload_pdc.json"
file_name = "Statique-data-KO-TotalEnergies.json"
with open(file_name, "r") as f:
    data = f.read()
payload_total = pd.read_json(StringIO(data), orient="record").reset_index(drop=True)
#payload

In [57]:
statiques = pd.read_csv("qualicharge-irve-statique.csv")

In [58]:
#statiques

In [59]:
statiques_total = statiques[statiques["nom_operateur"].str.contains("TotalEnergies", case=False, na=False)].reset_index()
payload = pd.concat([payload_total, statiques_total], ignore_index=True).rename(columns={"index": "old_index"}).drop_duplicates("id_pdc_itinerance").reset_index()

In [ ]:
#payload1 = pd.read_json("static_14h12m44s.json", orient="record")
#payload2 = pd.read_json("static_14h12m46s.json", orient="record")
#payload = pd.concat([payload1, payload2], ignore_index=True).reset_index()
payload = pd.read_json("bulk_evses_payload.json", orient="record").reset_index()

In [3]:
# create a Dataframe with an "index" column (example with json data)
payload = pd.read_json("request_2.json", orient="record").reset_index()

In [39]:
fields_payload = set(payload.columns)
#fields_payload
len(payload)

78731

In [60]:
payload

,index,reservation,nom_amenageur,siren_amenageur,contact_amenageur,nom_operateur,contact_operateur,telephone_operateur,nom_enseigne,id_station_itinerance,...,paiement_cb,paiement_autre,tarification,condition_acces,horaires,accessibilite_pmr,restriction_gabarit,station_deux_roues,observations,old_index
0,0,True,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,185169402,Belib',FRV75P900102,...,False,True,NaN,Accès libre,24/7,Non accessible,aucune restriction connue,False,NaN,NaN
1,1,True,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,185169402,Belib',FRV75P900102,...,False,True,NaN,Accès libre,24/7,Non accessible,aucune restriction connue,False,NaN,NaN
2,2,True,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,185169402,Belib',FRV75P900102,...,False,True,NaN,Accès libre,24/7,Non accessible,aucune restriction connue,False,NaN,NaN
3,3,True,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,185169402,Belib',FRV75P900101,...,False,True,NaN,Accès libre,24/7,Non accessible,aucune restriction connue,False,NaN,NaN
4,4,True,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,185169402,Belib',FRV75P900101,...,False,True,NaN,Accès libre,24/7,Non accessible,aucune restriction connue,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8039,8960,True,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,tel:+33-1-85-16-94-02,Belib',FRV75PPX1801,...,False,True,NaN,Accès libre,24/7,Non accessible,aucune restriction connue,True,NaN,74959.0
8040,8961,False,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,tel:+33-1-85-16-94-02,TotalEnergies Charge Rapide,FRHPCPNF059775TOTEMSA,...,False,True,NaN,Accès libre,24/7,Accessibilité inconnue,aucune restriction connue,False,NaN,75515.0
8041,8962,False,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,tel:+33-1-85-16-94-02,TotalEnergies Charge Rapide,FRHPCPNF059775TOTEMSA,...,False,True,NaN,Accès libre,24/7,Accessibilité inconnue,aucune restriction connue,False,NaN,76780.0
8042,8963,False,TotalEnergies Marketing France,531680445,supervision-ev.france@totalenergies.com,TotalEnergies Marketing France,supervision-ev.france@totalenergies.com,tel:+33-1-85-16-94-02,TotalEnergies Charge Rapide,FRHPCPNF059775TOTEMSA,...,False,True,NaN,Accès libre,24/7,Accessibilité inconnue,aucune restriction connue,False,NaN,76811.0
8043,8964,False,TotalEnergies Charging Services,844192443,supervision-ev.france@totalenergies.com,TotalEnergies Charging Services,supervision-ev.france@totalenergies.com,tel:+33-4-83-56-80-09,Iléwat,FRMELPRES5912601,...,False,True,NaN,Accès libre,24/7,Accessibilité inconnue,aucune restriction connue,False,NaN,77296.0

In [61]:
# create the schema with the Qualicharge constraints between fields
schema = {
    'relationships': [
         # relation unicité des pdl
         {"fields": ["id_pdc_itinerance", "index"],                    "link" : "coupled" },   
         # relations inter entités
         {"fields": ["id_station_itinerance", "nom_amenageur"],        "link" : "derived" },
         {"fields": ["id_station_itinerance", "siren_amenageur"],      "link" : "derived" },
         {"fields": ["id_station_itinerance", "contact_amenageur"],    "link" : "derived" },
         {"fields": ["id_station_itinerance", "nom_operateur"],        "link" : "derived" },
         {"fields": ["id_station_itinerance", "contact_operateur"],    "link" : "derived" },
         {"fields": ["id_station_itinerance", "telephone_operateur"],  "link" : "derived" },
         {"fields": ["id_station_itinerance", "nom_enseigne"],         "link" : "derived" },
         {"fields": ["id_station_itinerance", "coordonneesXY"],        "link" : "derived" },
         {"fields": ["id_pdc_itinerance", "id_station_itinerance"],    "link" : "derived" },
         # relations intra entité - station
         {"fields": ["id_station_itinerance", "nom_station"],          "link" : "derived" },
         {"fields": ["id_station_itinerance", "implantation_station"], "link" : "derived" },
         {"fields": ["id_station_itinerance", "date_maj"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "num_pdl"],              "link" : "derived" },
         {"fields": ["id_station_itinerance", "id_station_local"],     "link" : "derived" },
         {"fields": ["id_station_itinerance", "nbre_pdc"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "condition_acces"],      "link" : "derived" },
         {"fields": ["id_station_itinerance", "horaires"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "station_deux_roues"],   "link" : "derived" },
         {"fields": ["id_station_itinerance", "raccordement"],         "link" : "derived" },
         {"fields": ["id_station_itinerance", "date_mise_en_service"], "link" : "derived" },
         # relations intra entité - localisation
         {"fields": ["coordonneesXY", "adresse_station"],              "link" : "derived" },
         {"fields": ["coordonneesXY", "code_insee_commune"],           "link" : "derived" }
    ]
}
fields_schema = set([field for relation in schema['relationships'] for field in relation['fields']])

In [62]:
# identify the difference between payload and schema
fields_errors = fields_schema - fields_payload
fields_errors

set()

In [63]:
schema_reduce = {'relationships': [relation for relation in schema['relationships'] if not(set(relation['fields']) & fields_errors)]}
#schema_reduce

In [64]:
# calculate the errors dictionnary (keys : schema constraint, values : list of index with a constraint error
dic_errors = Cdataset(payload).check_relationship(schema_reduce)
{key: val for key, val in dic_errors.items() if val}

{'telephone_operateur - id_station_itinerance': (284,
  285,
  286,
  7693,
  287,
  288,
  289,
  3752,
  293,
  294,
  295,
  5061,
  328,
  1213,
  4933,
  6182,
  6404,
  909,
  910,
  7174),
 'num_pdl - id_station_itinerance': (284,
  285,
  286,
  7693,
  287,
  288,
  289,
  3752,
  293,
  294,
  295,
  5061,
  328,
  1213,
  4933,
  6182,
  6404,
  909,
  910,
  7174),
 'raccordement - id_station_itinerance': (284,
  285,
  286,
  7693,
  287,
  288,
  289,
  3752,
  293,
  294,
  295,
  5061),
 'adresse_station - coordonneesXY': (788, 789, 790, 791, 792, 793, 794),
 'code_insee_commune - coordonneesXY': (284,
  285,
  286,
  7693,
  287,
  288,
  289,
  3752,
  293,
  294,
  295,
  5061,
  328,
  1213,
  4933,
  6182,
  6404,
  909,
  910,
  7174,
  985,
  989,
  990,
  5014,
  5309,
  7950)}

In [79]:
# example of error
errors = payload.loc[dic_errors['code_insee_commune - coordonneesXY'], ['coordonneesXY', 'code_insee_commune', 'id_station_itinerance', 'id_pdc_itinerance']]
#errors['id_station_itinerance'].unique()

In [80]:
#errors.loc[errors['id_station_itinerance'] == 'FRAU1P00810000', :]
errors

,coordonneesXY,code_insee_commune,id_station_itinerance,id_pdc_itinerance
284,"[2.81979, 49.41517]",60159,FRTCBP03301,FRTCBE012787
285,"[2.81979, 49.41517]",60159,FRTCBP03301,FRTCBE012788
286,"[2.81979, 49.41517]",60159,FRTCBP03301,FRTCBED001445
7693,"[2.81979, 49.41517]",60159,FRTCBP03301,FRTCBE012789
287,"[2.82308, 49.41911]",60159,FRTCBP03302,FRTCBE012790
288,"[2.82308, 49.41911]",60159,FRTCBP03302,FRTCBE012791
289,"[2.82308, 49.41911]",60159,FRTCBP03302,FRTCBED00144
3752,"[2.82308, 49.41911]",60159,FRTCBP03302,FRTCBE012792
293,"[2.83259, 49.4111]",60159,FRTCBP03304,FRTCBE012796
294,"[2.83259, 49.4111]",60159,FRTCBP03304,FRTCBE012797
295,"[2.83259, 49.4111]",60159,FRTCBP03304,FRTCBED001680
5061,"[2.83259, 49.4111]",60159,FRTCBP03304,FRTCBED001534
328,"[2.344388, 48.86502]",75102,FRV75PPX0205,FRV75EPX02051
1213,"[2.344388, 48.86502]",75102,FRV75PPX0205,FRV75EPX02054
4933,"[2.344388, 48.86502]",75102,FRV75PPX0205,FRV75EPX02055
6182,"[2.344388, 48.86502]",75102,FRV75PPX0205,FRV75EPX02052
6404,"[2.344388, 48.86502]",75102,FRV75PPX0205,FRV75EPX02053
909,"[3.069109, 50.603071]",59220,FRMELPRES5915501,FRMELERES591550121
910,"[3.069109, 50.603071]",59220,FRMELPRES5915501,FRMELERES591550131
7174,"[3.069109, 50.603071]",59220,FRMELPRES5915501,FRMELEINT591550111
985,"[2.885711, 50.613716]",59303,FRMELPRES5913406,FRMELERES591340611
989,"[2.885711, 50.613716]",59303,FRMELPRES5913406,FRMELERES591340621
990,"[2.885711, 50.613716]",59303,FRMELPRES5913406,FRMELERES591340631
5014,"[2.885711, 50.613716]",59303,FRMELPRES5913401,FRMELERES591340111
5309,"[2.885711, 50.613716]",59303,FRMELPRES5913401,FRMELERES591340131
7950,"[2.885711, 50.613716]",59303,FRMELPRES5913401,FRMELERES591340121

In [69]:
# example of error
errors = payload.loc[dic_errors['telephone_operateur - id_station_itinerance'], ['telephone_operateur', 'id_station_itinerance', 'id_pdc_itinerance']]
#errors['id_station_itinerance'].unique()

In [70]:
#errors.loc[errors['id_station_itinerance'] == 'FRAU1P00810000', :]
errors

        telephone_operateur id_station_itinerance   id_pdc_itinerance
284               483568009           FRTCBP03301        FRTCBE012787
285               483568009           FRTCBP03301        FRTCBE012788
286               483568009           FRTCBP03301       FRTCBED001445
7693  tel:+33-4-83-56-80-09           FRTCBP03301        FRTCBE012789
287               483568009           FRTCBP03302        FRTCBE012790
288               483568009           FRTCBP03302        FRTCBE012791
289               483568009           FRTCBP03302        FRTCBED00144
3752  tel:+33-4-83-56-80-09           FRTCBP03302        FRTCBE012792
293               483568009           FRTCBP03304        FRTCBE012796
294               483568009           FRTCBP03304        FRTCBE012797
295               483568009           FRTCBP03304       FRTCBED001680
5061  tel:+33-4-83-56-80-09           FRTCBP03304       FRTCBED001534
328               185169402          FRV75PPX0205       FRV75EPX02051
1213  tel:+33-1-85-16-94-02          FRV75PPX0205       FRV75EPX02054
4933  tel:+33-1-85-16-94-02          FRV75PPX0205       FRV75EPX02055
6182  tel:+33-1-85-16-94-02          FRV75PPX0205       FRV75EPX02052
6404  tel:+33-1-85-16-94-02          FRV75PPX0205       FRV75EPX02053
909               483568009      FRMELPRES5915501  FRMELERES591550121
910               483568009      FRMELPRES5915501  FRMELERES591550131
7174  tel:+33-4-83-56-80-09      FRMELPRES5915501  FRMELEINT591550111