# Tests des fonctions de calcul de la saturation - full chunk

découpage 1 : à partir des pools
découpage 2 : à partir des stations (après élimination des stations déja traitées)

In [1]:
from datetime import date

import pandas as pd
from e2_e3_e6 import e2_e3_e6

CHUNK_SIZE: int = 20 #0
SAMPLES: int = 288  # 5 min
SATURE_H: int = 45  # minimum duration (min) of saturation to have a saturated hour
MAX_SESSION_DURATION_HOURS = 24

ID_POC: str = "id_pdc_itinerance"
ID_STATION: str = "id_station_itinerance"
ID_POOL: str = "id_pool"
SATURATION_RATIO = 0.1
OVERLOAD_RATIO = 0.2
MIN_POWER = 75

#day = date(2026,7, 5)
#day = date(2026,7, 14)
day = date(2026,8, 1)
#day = date(2026,8, 18)
#day = date(2026,8, 25)
date_file = f"{day.year}{day.month:02d}{day.day:02d}"

data_quali = "../data/"

## test qualicharge

In [2]:
state_poc, state_station, state_pool = e2_e3_e6(MIN_POWER, day, CHUNK_SIZE, SAMPLES)

70 218
344 1105
460 1557
89 209
179 588
251 1132
196 514
137 366
415 949
489 1613
348 1170
390 1168
321 1073
553 2190
114 321
480 1555
224 298
161 478
467 1637
393 1485
277 683
78 182
266 599
248 596
366 1314
317 1019
397 1346
414 1085
204 1018
201 654
231 706
394 1091
183 207
403 1419
357 645
261 488
293 1041
374 1026
295 642
466 1232
350 1055
237 765
262 769
249 940
240 646
200 980
172 435
311 837
356 888
199 258
249 825
238 683
286 1210
325 998
498 1245
293 821
283 992
284 951
228 836
342 1196
703 2836
224 738
259 700
396 1247
117 472
374 1119
278 883
190 472
193 0
215 874
250 815
148 152
267 1403
250 593
191 908
202 524
310 1199
305 1010
256 766
148 559
533 2927
221 674
198 407
269 925
591 2005
456 1768
97 258
502 1580
156 778
399 1457
242 741
248 738
291 991
224 674
307 1216
349 999
448 1222
192 553
216 544
410 1554
232 872
376 1303
180 610
470 1511
103 271
465 1255
235 562
313 1495
365 1716
139 942
292 675
93 642
344 1755
457 1795
120 346
522 2117
291 1234
570 2886
170 421
318 892
247 841
411 1094
351 1081
348 1312
112 313
367 1139
221 772
160 487
149 329
271 1139
186 550
352 1336
282 1117
469 1422
402 1501
0 0
197 1595
87 276
129 311
111 389
224 687
197 810
122 290
149 331
284 679
192 149
232 0
166 589
148 359
576 1956
286 760
330 976
622 1998
157 997
428 1594
437 1479
194 508
112 277
227 0
446 2067
133 0
211 1220
200 488
383 1160
157 615
111 287
148 438
190 504
326 961
615 1590
712 1820
516 1621
205 960
153 427
249 615
67 219
222 981
16 66
240 683
300 678
258 567
555 1692
203 986
580 1519
379 1330
193 502
232 739
198 713
446 1402
102 429
327 904
274 716
124 570
260 813
674 1891
179 514
284 802
207 718
91 320
363 1125
54 134
90 209
350 1203
199 644
42 129
255 833
115 739
252 727
326 790
759 2361
192 766
246 964
383 1147
27 92
32 391
145 0
77 0
136 0
58 0
77 0
75 0
61 0
25 0
56 0
73 0
74 0
65 0
110 0
77 0
84 0
40 0
95 0
90 0
88 0
57 0
80 0
41 0
74 0
83 0
80 0
82 0
86 0
57 0
28 0
58 0
15 0
62 0
56 219
51 339
42 336
61 556
32 217
65 458
36 280
78 719
32 255
54 558
108 749
134 1069
54 353
35 262
56 516
54 421
106 808
60 410
85 575
54 391
78 562
38 265
25 440
51 513
37 274
93 1542
26 208
88 1365
72 690
83 690
50 417
120 871
40 296
147 1425
76 712
85 20948
33 866
79 656
95 792
43 587
120 1096
70 555
8 54
107 960
48 350
18 117
3 4
3 6
21 53
39 124
33 112
27 101
35 146
84 378
52 232
34 163
80 401
81 382
129 678
111 523
127 697
80 392
21 104
67 345
36 173
40 229
59 314
51 513
88 595
2 19
128 982
27 214
40 662
14 154
81 576
41 702
133 1168
30 376
104 1039
25 409
58 485
16 41
20 57
17 47
7 14
59 141
45 111
89 206
23 62
31 72
18 43
41 137
54 220
36 86
58 254
83 887
35 254
62 491
46 250
19 151
34 427
54 788
65 1282
76 909
70 762
42 435
41 297
33 454
60 709
73 425
114 1020
50 115
126 320
66 146
52 119
30 67
78 166
72 164
52 111
42 94
46 96
37 123
20 60
26 84
31 82
31 92
27 64
22 50
35 84
19 60
51 139
38 95
38 103
26 69
22 65
19 52
20 53
232 555
223 523
109 294
194 414
154 332
126 306
288 647
90 209
195 435
224 538
167 396
194 487
149 338
158 362
109 234
202 465
109 265
205 465
85 194
236 561
160 384
533 1259
270 605
149 373
122 291
129 297
139 332
134 289
159 374
136 302
207 466
121 287
187 445
108 264
143 317
271 656
213 488
219 472
127 288
112 348
217 485
143 354
219 507
215 487
152 370
242 542
96 387
266 595
136 292
148 368
149 327
193 481
298 677
82 188
225 489
336 800
207 483
240 526
226 511
165 394
165 375
125 272
149 323
258 580
155 342
129 296
154 347
234 577
232 543
183 408
259 591
152 344
140 311
346 777
193 442
204 516
224 492
221 510
231 540
227 512
129 296
91 201
125 277
223 469
249 598
166 368
232 491
132 295
144 387
206 479
107 243
141 316
123 264
198 474
206 444
172 455
323 725
54 131
155 344
53 108
122 274
74 168
14 48
92 428
43 200
53 180
80 330
43 147
21 83
57 222
22 70
30 99
35 118
18 56
5 22
18 70
33 111
19 61
15 47
5 18
24 75
54 220
26 91
25 84
30 102
101 403
21 80
49 178
22 68
26 78
22 75
21 72
40 137
96 467
64 242
25 164
61 275
32 188
62 143
135 0
158 0
117 0
209 0
166 0
122 0
101 0
190 0
201 0
141 0
154 0
186 0
197 0
142 0
197 0
174 0
138 0
161 0
100 0
212 0
179 0
194 0
185 0
164 0
130 0
182 0
179 0
162 0
135 0
133 0
159 0
216 0
110 0
199 0
107 0
132 0
132 0
99 0
161 0
134 0
100 0
128 0
104 0
150 16
49 104
50 110
46 109
89 171
63 123
67 149
65 140
71 145
22 57
59 123
21 42
57 138
77 165
50 101
47 120
79 208
76 163
76 172
53 114
82 168
73 160
52 99
79 165
32 65
84 202
27 57
54 113
45 100
39 130
41 84
120 292
88 195
55 118
48 105
76 175
62 128
26 56
98 215
109 226
47 108
107 219
55 119
147 324
96 315
54 182
134 538
113 422
31 220
106 467
215 751
152 544
243 994
72 632
25 59
52 128
37 26
55 0
20 1165
16 127
18 175
35 781
17 182
83 212
52 222
43 113
95 244
145 460
107 322
35 95
70 180
39 94
89 238
55 134
126 293
181 589
26 72
56 134
28 87
27 78
56 159
50 162
80 260
89 261
126 315
68 183
21 45
47 142
87 258
138 349
63 196
60 193
33 90
15 35
154 392
51 119
63 182
120 278
78 229
50 194
134 422
51 146
64 202
39 108
57 287
100 666
39 878
15 87
15 47
32 236
35 209
45 261
55 376
31 204
35 188
49 226
16 163
32 153
40 297
49 369
30 343
36 263
19 200
31 269
27 126
35 87
58 143
32 85
47 147
65 151
48 129
20 42
31 67
25 64
41 101
92 211
126 325
176 594
222 819
239 844
320 1030
114 844
259 839
270 989
228 798
234 733
217 713
300 923
177 595
124 434
357 1142
148 435
179 595
163 729
254 875
154 657
114 514
204 4198
298 1264
44 151
107 265
115 278
133 364
175 438
184 429
147 351
139 318
122 312
181 397
102 251
73 191
118 292
108 239
124 289
124 345
134 344
141 320
141 305
113 254
126 276
123 320
169 401
146 423
86 199
111 299
120 278
138 312
119 281
89 208
140 323
85 185
117 282
100 304
148 401
76 174
172 389
132 311
121 273
168 407
81 189
99 232
137 294
76 159
241 531
117 282
105 244
112 255
167 399
128 279
143 322
154 348
184 417
131 317
97 222
78 169
134 302
95 239
116 282
88 190
149 372
128 289
128 311
77 174
142 305
94 223
131 304
161 361
122 283
106 266
133 291
199 1597
119 271
114 258
143 350
158 385
124 275
171 399
146 346
60 229
75 194
75 260
69 264
42 223
137 449
93 261
105 315
39 93
52 191
65 175
101 293
90 241
65 172
88 234
36 109
107 277
70 315
60 376
42 174
49 158
80 195
79 218
80 220
85 203
122 298
105 385
23 78
88 222
101 265
54 137
85 223
69 181
53 116
90 231
106 287
57 159
121 297
75 183
97 253
42 103
44 104
54 172
98 253
108 284
81 199
98 215
88 218
73 385
119 338
105 251
85 245
74 211
82 292
91 365
62 230
144 360
116 431
45 107
134 351
84 223
98 254
150 382
31 91
65 260
80 292
65 198
92 268
87 278
134 323
68 180
81 718
63 210
83 224
71 204
70 186
94 241
92 337
47 152
50 142
78 191
25 70
119 390
61 172
102 307
47 166
95 292
95 288
102 295
133 430
104 323
52 152
60 196
49 133
81 263
46 130
60 180
48 139
143 467
68 219
25 81
43 196
58 268
31 138
32 110
28 132
39 136
22 92
0 0
0 0
1 3
30 212
35 255
71 405
9 53
19 111
31 119
26 77
35 144
39 127
52 168
87 364
58 183
23 91
52 145
66 232
58 267
53 229
61 150
139 493
11 47
66 322
41 115
28 89
61 424
70 223
77 247
30 124
21 84
77 222
5 21
21 85
37 147
41 120
36 129
55 390
28 99
84 240
101 280
42 159
74 321
89 265
71 220
79 255
7 23
78 257
44 136
26 72
37 110
10 31
38 145
74 195
49 151
18 49
39 120
105 319
42 145
46 131
27 82
44 145
54 156
13 46
59 179
42 113
49 237
66 234
28 80
74 222
45 240
67 171
56 172
57 3499
39 156
84 715
45 218
65 202
68 239
45 120
33 108
8 34
46 196
70 220
65 337
26 74
60 248
43 164
38 123
31 96
21 63
43 159
52 235
63 230
64 221
37 147
14 38
27 96
17 54
39 111
72 474
32 91
39 198
46 167
65 222
51 164
58 218
26 106
37 136
41 106
33 94
44 155
24 191
48 137
32 99
61 173
51 202
102 374
20 58
46 130
66 204
91 2533
78 269
61 217
79 263
119 506
32 87
82 274
46 176
66 235
77 518
18 53
49 131
38 137
56 157
67 234
19 59
38 112
78 280
47 201
65 290
56 153
35 100
43 171
62 206
46 140
67 210
22 86
32 94
117 327
41 203
25 106
34 110
45 124
18 63
33 99
40 123
68 185
21 65
27 79
27 80
22 62
50 143
27 73
34 105
15 40
30 90
32 154
95 366
71 255
34 189
85 489
53 137
52 190
26 91
75 208
102 499
25 82
37 120
77 251
48 134
11 39
100 270
68 241
39 151
10 37
74 292
65 208
82 228
69 178
33 132
48 132
89 260
48 506
32 85
63 199
24 129
108 291
58 199
24 118
83 381
83 232
85 814
64 159
64 205
85 255
48 187
62 198
30 80
82 256
79 219
103 275
52 174
22 87
74 241
27 146
37 232
8 58
29 216
8 64
19 126
30 230
13 86
30 202
14 78
27 170
35 227
47 267
29 113
67 309
26 369
73 707
73 458
61 566
28 361
35 483
20 97
20 135
27 106
28 232
43 523
37 480
28 406
43 751
61 518
71 616
33 375
23 372
49 665
43 166
26 472
16 89
25 131
35 187
25 136
12 68
23 122
38 92
98 232
73 244
22 76
43 104
69 234
35 127
34 85
66 49
100 44
16 4
42 0
30 85
31 123
31 109
67 176
95 228
57 181
17 50
54 128
25 60
15 38
81 317
424 1215
201 576
424 1051
579 1617
524 1947
381 1076
300 818
666 1713
187 638
551 1476
142 684
267 744
458 1344
234 607
552 1756
803 2330
465 1453
325 825
257 855
251 730
216 721
489 1321
230 619
409 1219
200 765
114 344
505 1526
211 605
136 364
502 1485
236 702
239 899
345 1155
220 968
249 809
113 513
344 1169
192 589
293 1080
424 1145
647 1572
211 617
476 1472
296 978
329 989
321 981
258 823
438 1520
258 759
345 1237
380 1377
158 478
214 806
221 745
313 979
234 949
246 763
218 719
416 1068
306 825
313 1076
600 1548
473 1493
161 532
237 806
312 1108
95 338
383 1076
400 1151
252 1005
396 1332
260 940
406 1481
451 1140
165 579
796 2375
519 1217
463 1191
257 832
620 1564
386 1185
261 708
313 927
289 891
132 445
562 1604
349 1003
218 659
481 1571
454 1250
100 328
504 1396
255 814
91 437
599 1574
73 363
369 966
438 1243
137 445
259 894
493 1359
153 583
734 2135
117 379
402 1327
330 1044
341 903
356 1109
374 1233
218 930
419 1232
348 949
687 1915
154 459
371 1074
426 1187
135 580
294 1054
232 802
265 813
165 612
289 901
203 598
247 746
605 1725
121 353
373 1093
238 681
187 628
527 1239
563 1562
430 1363
554 1444
113 357
437 1334
293 845
459 1261
369 1024
234 821
189 552
761 1755
130 580
127 566
218 816
272 823
443 1075
332 847
95 324
576 1529
56 492
361 1090
228 744
144 406
432 1315
530 1250
675 1672
447 1350
115 406
758 2480
294 1085
317 884
236 868
221 757
270 804
196 619
312 953
504 1444
37 109
27 88
31 93
19 52
36 128
40 128
31 89
44 160
42 123
42 148
57 192
98 344
62 188
36 127
21 81
42 182
52 195
45 142
19 82
56 186
57 218
34 101
60 147
100 362
82 251
211 492
53 142
115 326
135 340
101 121
39 12
52 62
52 168
52 158
182 586
46 190

In [3]:
state_poc.sort_values(by=[ID_POC])

,id_pdc_itinerance,occupe,occupe_max,hors_service,libre,pseudo_libre,pseudo_occupe
4135,FR3R3E10001456611,70.0,60.0,0.0,1370.0,70.0,0.0
4136,FR3R3E10001456612,80.0,45.0,0.0,1360.0,80.0,0.0
4137,FRALDE100541,145.0,55.0,0.0,1295.0,0.0,0.0
4138,FRALDE100551,170.0,60.0,0.0,1270.0,0.0,15.0
4139,FRALDE100552,90.0,45.0,0.0,1350.0,0.0,0.0
...,...,...,...,...,...,...,...
23341,FRZUNEFR8601ER06,220.0,55.0,15.0,1205.0,0.0,5.0
23342,FRZUNEFR8801ER01,175.0,60.0,0.0,1265.0,0.0,0.0
23343,FRZUNEFR8801ER02,140.0,55.0,0.0,1300.0,0.0,0.0
23344,FRZUNEFR8801ER03,65.0,35.0,0.0,1375.0,0.0,5.0
23345,FRZUNEFR8801ER04,185.0,50.0,0.0,1255.0,0.0,0.0

In [4]:
state_station.sort_values(by=[ID_STATION])

,id_station_itinerance,nb_pdc,hs,inactif,pu_cum,sature_cum,surcharge,actif,sature_max,pu_max,pu_len
505,FR3R3P89882136,2,0.0,1290.0,0.0,0.0,0.0,150.0,0.0,0.0,0.0
506,FRALDPFR00916,8,0.0,1220.0,0.0,0.0,0.0,220.0,0.0,0.0,0.0
507,FRALDPFR00950,8,0.0,995.0,0.0,0.0,5.0,440.0,0.0,0.0,0.0
508,FRALLPGO000007,6,0.0,830.0,340.0,205.0,170.0,235.0,60.0,60.0,230.0
509,FRALLPGO000013,10,0.0,395.0,0.0,0.0,40.0,1005.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
5479,FRZUNP6023950095875504781,8,0.0,570.0,120.0,25.0,60.0,785.0,15.0,55.0,55.0
5480,FRZUNP6927750076048540479,8,0.0,1090.0,0.0,0.0,0.0,350.0,0.0,0.0,0.0
373,FRZUNP7329346578064027187,25,0.0,175.0,0.0,0.0,0.0,1265.0,0.0,0.0,0.0
5481,FRZUNP8610050047391683219,6,0.0,1000.0,235.0,20.0,115.0,305.0,20.0,60.0,150.0
5482,FRZUNP8813050087046756891,4,0.0,1070.0,10.0,5.0,0.0,365.0,5.0,10.0,10.0

In [5]:
state_station[state_station[ID_STATION] == 'FRIOYP13530834']

,id_station_itinerance,nb_pdc,hs,inactif,pu_cum,sature_cum,surcharge,actif,sature_max,pu_max,pu_len
152,FRIOYP13530834,6,0.0,35.0,925.0,420.0,400.0,585.0,55.0,60.0,480.0

In [6]:
state_station[state_station['pu_len'] >= 180]

,id_station_itinerance,nb_pdc,hs,inactif,pu_cum,sature_cum,surcharge,actif,sature_max,pu_max,pu_len
1,FRIOYP13531046,6,0.0,260.0,475.0,170.0,210.0,800.0,45.0,60.0,345.0
3,FRFASP11568703,8,0.0,320.0,330.0,90.0,155.0,875.0,35.0,60.0,330.0
14,FRHPCPNF059788TOTEM,21,0.0,25.0,220.0,90.0,135.0,1190.0,35.0,60.0,220.0
15,FRIOYP13530786,8,0.0,15.0,985.0,295.0,505.0,625.0,35.0,60.0,475.0
23,FRIOYP13530844,16,0.0,75.0,260.0,110.0,155.0,1100.0,40.0,60.0,235.0
...,...,...,...,...,...,...,...,...,...,...,...
5297,FRTSLP34053,20,0.0,85.0,275.0,55.0,130.0,1170.0,35.0,60.0,250.0
5304,FRTSLP4003025,16,0.0,490.0,280.0,85.0,195.0,670.0,30.0,60.0,230.0
5344,FRTSLP45349,9,0.0,280.0,415.0,140.0,160.0,860.0,45.0,60.0,315.0
5418,FRVIAP124001,4,360.0,830.0,620.0,45.0,0.0,205.0,25.0,60.0,620.0
5462,FRYAWP90938287,6,0.0,470.0,390.0,145.0,205.0,620.0,40.0,60.0,225.0

In [7]:
state_pool[state_pool['pu_len'] >= 180]

,id_pool,nb_pdc,hs,inactif,pu_cum,sature_cum,surcharge,actif,sature_max,pu_max,pu_len
3,A000004,8,0.0,320.0,330.0,90.0,155.0,875.0,35.0,60.0,330.0
12,A000019,21,0.0,25.0,220.0,90.0,135.0,1190.0,35.0,60.0,220.0
15,A000024,8,0.0,15.0,985.0,295.0,505.0,625.0,35.0,60.0,475.0
21,A000039,16,0.0,75.0,260.0,110.0,155.0,1100.0,40.0,60.0,235.0
23,A000046,14,0.0,195.0,385.0,185.0,135.0,925.0,40.0,60.0,325.0
...,...,...,...,...,...,...,...,...,...,...,...
453,A001418,8,0.0,1400.0,1120.0,40.0,0.0,0.0,40.0,60.0,1120.0
459,A001618,6,0.0,120.0,785.0,375.0,325.0,620.0,45.0,60.0,715.0
470,A001675,12,0.0,90.0,355.0,160.0,125.0,1065.0,55.0,60.0,230.0
472,A001685,6,0.0,55.0,810.0,375.0,270.0,740.0,45.0,60.0,420.0
473,A001698,12,0.0,455.0,320.0,170.0,120.0,695.0,50.0,60.0,310.0

In [8]:
state_pool[state_pool[ID_POOL] == 'A000377']

,id_pool,nb_pdc,hs,inactif,pu_cum,sature_cum,surcharge,actif,sature_max,pu_max,pu_len
145,A000377,6,0.0,35.0,925.0,420.0,400.0,585.0,55.0,60.0,480.0

In [9]:
state_pool.sort_values(by=[ID_POOL])

,id_pool,nb_pdc,hs,inactif,pu_cum,sature_cum,surcharge,actif,sature_max,pu_max,pu_len
0,A000001,11,0.0,660.0,0.0,0.0,0.0,780.0,0.0,0.0,0.0
1,A000002,16,0.0,170.0,10.0,0.0,40.0,1230.0,0.0,10.0,10.0
2,A000003,16,0.0,385.0,25.0,10.0,30.0,1015.0,5.0,25.0,25.0
3,A000004,8,0.0,320.0,330.0,90.0,155.0,875.0,35.0,60.0,330.0
4,A000005,8,0.0,585.0,120.0,25.0,75.0,755.0,15.0,50.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...
471,A001679,10,0.0,1000.0,0.0,0.0,0.0,440.0,0.0,0.0,0.0
472,A001685,6,0.0,55.0,810.0,375.0,270.0,740.0,45.0,60.0,420.0
473,A001698,12,0.0,455.0,320.0,170.0,120.0,695.0,50.0,60.0,310.0
474,A001701,2,0.0,1145.0,10.0,0.0,0.0,295.0,0.0,10.0,10.0
475,A001859,3,0.0,920.0,260.0,30.0,0.0,490.0,15.0,60.0,140.0