# Validation e2-e3

In [ ]:
import json

import geopandas as gpd
import pandas as pd

In [5]:
e2_str = pd.read_csv("../../data_DMR_e2_e3/e2_e3_05-07-2026.csv")["extras"][0]
e2_pdc = pd.DataFrame(json.loads(e2_str))

e3_str = pd.read_csv("../../data_DMR_e2_e3/e2_e3_05-07-2026.csv")["extras"][1]
e3_station = pd.DataFrame(json.loads(e3_str))

In [6]:
e2_pdc

       libre  occupe  hors_service  id_pdc_itinerance
0     1215.0   225.0           0.0    FRALLEGO0002061
1     1345.0    95.0           0.0    FRALLEGO0020911
2     1400.0    40.0           0.0    FRALLEGO0020912
3     1235.0   205.0           0.0    FRALLEGO0020921
4     1385.0    55.0           0.0    FRALLEGO0020922
...      ...     ...           ...                ...
1510  1190.0   250.0           0.0       FRMBIEVGODS2
1511  1375.0    65.0           0.0    FRTLSE311490503
1512  1040.0   400.0           0.0  FRVIAE10001221121
1513  1120.0   320.0           0.0  FRVIAE10001476521
1514   945.0   495.0           0.0  FRVIAE10001476522

[1515 rows x 4 columns]

In [11]:
# FRHPCENF050462001
e2_pdc[e2_pdc['id_pdc_itinerance'].str[:14] == 'FRHPCENF050462']

       libre  occupe  hors_service  id_pdc_itinerance
1489   640.0   800.0           0.0  FRHPCENF050462001
1490   640.0   800.0           0.0  FRHPCENF050462002
1491  1220.0   220.0           0.0  FRHPCENF050462004

In [10]:
e3_station[(e3_station['sature_max']>40) & (e3_station['nb_pdc']>2)]

,hs,nb_h,actif,nb_pdc,inactif,surcharge,sature_cum,sature_max,id_station_itinerance
73,0.0,24,0.0,4,1370.0,0.0,70.0,60.0,FRALLPGO000434
118,0.0,24,110.0,4,1030.0,0.0,300.0,60.0,FRALLPGO000649
151,0.0,24,0.0,4,1360.0,0.0,80.0,50.0,FRALLPGO000811
153,0.0,24,0.0,4,1380.0,0.0,60.0,45.0,FRALLPGO000819
160,0.0,24,0.0,4,1335.0,0.0,105.0,50.0,FRALLPGO000881
161,0.0,24,0.0,4,1325.0,0.0,115.0,50.0,FRALLPGO000885
173,0.0,24,120.0,3,1275.0,0.0,45.0,45.0,FREVCP000122
354,0.0,24,650.0,4,585.0,0.0,205.0,55.0,FRHPCPNF050462
370,0.0,24,0.0,4,1375.0,0.0,65.0,60.0,FRTLSP31149050

In [ ]:
stations_pools_str = pd.read_csv("stations_pools_2026-07-25.csv")["extras"][0]
stations_pools = pd.DataFrame(json.loads(stations_pools_str))

stations_pdcs_str = pd.read_csv("stations_pdcs_2026-07-25.csv")["extras"][0]
stations_pdcs = pd.DataFrame(json.loads(stations_pdcs_str))

aires_dmr_gpd = gpd.read_file("aires_dmr_2026-07-08.geojson").rename(columns={"id_aire": "id_pool"})
aires_dmr = pd.DataFrame(aires_dmr_gpd[['Aire', 'NomUsuel', 'Nature', 'GVO', 'Surface', 'Réseau', 'Axe', 'GVO_Axe', 'id_pool']])